---
- name: Gather dns servers ip addresses
  setup:
    gather_subset: network
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups.all|select('match', '.*dns.*') |list  }}"

- name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload NetworkManager

- name: copy resolv
  template: src=resolv.conf
            dest="/etc/resolv.conf"
            owner=root
            group=root
            mode=0644




