---
- hosts: "*-PPRD-*dns*"
  become: yes
  become_user: root
  vars_files: ../vars/dns/main_ppd.yml
  roles:
    - role: ../roles/base      
    - role: ../roles/docker
    - role: ../roles/dns_client
    - role: ../roles/dns
    - role: ../roles/rsyslog_client
    - role: ../roles/zabbix-agent

- hosts: "*-PRD-*dns*"
  become: yes
  become_user: root
  vars_files: ../vars/dns/main_prd.yml
  roles:
    - role: ../roles/base
    - role: ../roles/docker
    - role: ../roles/dns_client
    - role: ../roles/dns
    - role: ../roles/rsyslog_client
    - role: ../roles/zabbix-agent
