---
- hosts: "*-PPRD-*nginx"
  gather_facts: yes
  become: yes
  become_user: root
  roles:
    - role: ../roles/base
    - role: ../roles/docker
    - role: ../roles/dns_client
    - role: ../roles/nginx
    - role: ../roles/rsyslog_client
    - role: ../roles/zabbix-agent

- hosts: "*-PRD-*nginx"
  gather_facts: yes
  become: yes
  become_user: root
  roles:
    - role: ../roles/base
    - role: ../roles/docker
    - role: ../roles/dns_client
    - role: ../roles/nginx
    - role: ../roles/rsyslog_client
    - role: ../roles/zabbix-agent

