---
- hosts: "*-PPRD-*ifconfig*"
  become: yes
  become_user: root
  roles:
    - role: ../roles/base      
    - role: ../roles/docker
    - role: ../roles/dns_client
    - role: ../roles/ifconfig
    - role: ../roles/rsyslog_client
    - role: ../roles/zabbix-agent

- hosts: "*-PRD-*ifconfig*"
  become: yes
  become_user: root
  roles:
    - role: ../roles/base
    - role: ../roles/docker
    - role: ../roles/dns_client
    - role: ../roles/ifconfig
    - role: ../roles/rsyslog_client
    - role: ../roles/zabbix-agent
