---
- hosts: all 
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: ../roles/base
    - role: ../roles/docker
    - role: ../roles/dns_client
    - role: ../roles/zabbix-agent

- hosts: all:!*rsyslog
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: ../roles/rsyslog_client


