---
- hosts: "*-PPRD-*:!*rsyslog"
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: ../roles/rsyslog_client

- hosts: "*-PRD-*:!*rsyslog"
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: ../roles/rsyslog_client



